version: '3.3'
services:
 php:
   volumes:
     - './apps/symfony-app/:/usr/src/app'

 nginx:
   volumes:
     - './apps/symfony-app/public/:/usr/src/app'
     - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
   ports:
     - '${NGINX_PORT}:80'

 adminer:
   ports:
     - '${ADMINER_PORT}:8080'